### ISSUE TITLE
it is not possible to create more than 1 statistic in leaderstats

### ISSUE THREAD

**Issue by Jaxmilian** [rustyspottedcatt/advanceddata#1]
when I add another Stats parent from leaderstats, the script does not work correctly
for example:
["Cash"] = {
			CurrentValue = 0,
			StarterValue = 0,
			Type = "NumberValue",
			Parent = "leaderstats", 
		},
		["TimePlayed"] = {
			CurrentValue = 0,
			StarterValue = 0,
			Type = "NumberValue",
			Parent = "leaderstats", 
		},

**Comment by rustyspottedcatt** [comment]
should be fixed in the newer version
